# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

project 'GenericKitDemo.xcodeproj'

def install_pods
    pod 'Alamofire', '~> 4.8'
    pod 'Alamofire-SwiftyJSON', '~> 3'
    pod 'ObjectMapper', '~> 3.4'
end

target 'GenericKitDemo' do
    install_pods
end
