# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
project 'MarvelDemo.xcodeproj'

def install_pods
    pod 'DemoKit', :path => '../DemoKit.podspec'
    pod 'SwiftyJSON', '~> 5'
end

target 'MarvelDemo' do
    install_pods
end
